from enum import Enum

class Alerts(Enum):
    NO_SERVICE = "NO_SERVICE"
    REDUCED_SERVICE = "REDUCED_SERVICE"
    SIGNIFICANT_DELAYS = "SIGNIFICANT_DELAYS"
    DETOUR = "DETOUR"
    ADDITIONAL_SERVICE = "ADDITIONAL_SERVICE"
    MODIFIED_SERVICE = "MODIFIED_SERVICE"
    OTHER_EFFECT = "OTHER_EFFECT"
    UNKNOWN_EFFECT = "UNKNOWN_EFFECT"
    STOP_MOVED = "STOP_MOVED"
    NO_EFFECT = "NO_EFFECT"
    ACCESSIBILITY_ISSUE = "ACCESSIBILITY_ISSUE"
    STATION_ISSUE = "STATION_ISSUE"
    SHUTTLE = "SHUTTLE"
    PARKING_ISSUE = "PARKING_ISSUE"
    DELAY = "DELAY"
    ESCALATOR_CLOSURE = "ESCALATOR_CLOSURE"
    ELEVATOR_CLOSURE = "ELEVATOR_CLOSURE"
    STOP_MOVE = "STOP_MOVE"
    TRACK_CHANGE = "TRACK_CHANGE"
    SERVICE_CHANGE = "SERVICE_CHANGE"
    SCHEDULE_CHANGE = "SCHEDULE_CHANGE"
    BIKE_ISSUE = "BIKE_ISSUE"
    DOCK_ISSUE = "DOCK_ISSUE"

USEFUL_ALERT_ATTRIBUTES = [
    Alerts.NO_SERVICE,
    Alerts.REDUCED_SERVICE,
    Alerts.SIGNIFICANT_DELAYS,
    Alerts.DETOUR,
    Alerts.ADDITIONAL_SERVICE,
    Alerts.MODIFIED_SERVICE,
    Alerts.SHUTTLE,
    Alerts.DELAY,
    Alerts.TRACK_CHANGE,
    Alerts.SERVICE_CHANGE,
    Alerts.SCHEDULE_CHANGE,
]